version: "3.2"
services:
  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    container_name: better_izivi_api
    volumes:
      - ./api:/api
      - ./tmp/bundle:/bundle
    working_dir: /api
    depends_on:
      - mysql
    env_file: 'api/.env'
    ports:
      - "28000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: better_izivi_frontend
    volumes:
      - ./frontend:/var/frontend
      - ./tmp/node_modules:/var/node_modules
    working_dir: /var/frontend
    ports:
      - "23000:80"
  mysql:
    image: mariadb:10.3.14
    container_name: better_izivi_db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "23306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: better_izivi_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "28080:80"
